exports.EMAIL_EXISTS = "email already exists";
exports.EMAIL_VERIFY = "email verifivcation";
exports.EMAIL_SENT = "email was sent please verify";
exports.EMAIL_FAILED = "email verification is failed";
exports.USER_VERIFIED = "User Verified now you can Login";
exports.EMAIL_NOT_REGISTER = "email doesnot register. Please register with this mail.";
exports.USER_VERIFICATION = "User Verification is Required. Please Verify Your Email."
exports.SUCCESS_LOGIN = "succesfully login ";
exports.FAILED_LOGIN = "failed to login, check your credentials. whether its correct or not";
exports.LOGOUT_SUCCESS = "logout successfully";